#todo: get docker stuff working...
#image: gcc:10.3.0

build:
  stage: build
  script:
    - sudo apt update && apt -y install make autoconf cmake openmpi-devel
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_CXX_FLAGS='-I\ /usr/lib/x86_64-linux-gnu/openmpi/include/ -L\ /usr/lib/x86_64-linux-gnu/openmpi/lib/'
    - make -j 2