#todo: get docker stuff working...
#image: gcc:10.3.0

.buildTemplate:
  stage: build
  tags:
    -build
  script:
    - mkdir build-$ccompiler
    - cd build-$ccompiler
    - cmake --DCMAKE_C_COMPILER="$ccompiler" -DCMAKE_CXX_COMPILER="$cxxcompiler" ..
    - make -j 2


GNU:
  extends: .buildTemplate
  variables:
    ccompiler: gcc-10
    cxxcompiler: g++-10

CLANG:
  extends: .buildTemplate
  variables:
    ccompiler: clang-10
    cxxcompiler: clang++-10