#todo: get docker stuff working...
#image: gcc:10.3.0

stages:
  - build
  - test

.buildTemplate:
  stage: build
  script:
    - mkdir build-$ccompiler
    - cd build-$ccompiler
    - cmake -DCMAKE_C_COMPILER="$ccompiler" -DCMAKE_CXX_COMPILER="$cxxcompiler" ..
    - make gridgenerator -j 2

UnitTest:
  stage: test
  script:
    - mkdir build-$ccompiler
    - cd build-$ccompiler
    - cmake -DCMAKE_C_COMPILER="gcc-10" -DCMAKE_CXX_COMPILER="g++-10" ..
    - make UnitTest -j 2
    - cd UnitTest
    - ./UnitTest --gtest_output="xml:report.xml"
  artifacts:
    when: always
    reports:
      junit: report.xml


GNU:
  extends: .buildTemplate
  variables:
    ccompiler: "gcc-10"
    cxxcompiler: "g++-10"

CLANG:
  extends: .buildTemplate
  variables:
    ccompiler: "clang-10"
    cxxcompiler: "clang++-10"
